---
spring:
  profiles: standalone
eureka:
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
 
---

spring:
  profiles: cluster
eureka:
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    register-with-eureka: true
    fetch-registry: true