---
spring:  
  cloud:
    config:
      uri: http://configserver:8888
  profiles: cluster
eureka:
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    register-with-eureka: true
    fetch-registry: true