---
spring:  
  cloud:
    config:
      uri: http://configserver:8888
  profiles: standalone
eureka:
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
 