spring:
  profiles: amqp 
  rabbitmq:
    host: mosquito.rmq.cloudamqp.com
    port: 5672
    virtual-host: mnrvwrbj
    username: mnrvwrbj
    password: RnAVRqttZHMeSMmZEZJMfTcf7Wg2ACl6 
	cloud:
    	config:
      		uri: http://configserver:8888